name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature-model-training
      - feature-app
      - feature-api
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Tests
      run: |
        pytest test.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Vercel
      run: |
        npm install -g vercel
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
